### ISSUE TITLE
Stop Calibration if a charger was disconnected

### ISSUE THREAD

**Issue by rimusz** [davidwernhart/AlDente-Pro-Bug-Tracking#10]
Would be good to improve Calibration by stopping it if a charger was disconnected, as otherwise it will drain the battery completely.

**Comment by davidwernhart** [comment]
Hey @rimusz 

thank you for the feedback!
You are right, that absolutely makes sense.
We will include it in a future update :)

Best regards,
David

**Comment by rimusz** [comment]
cool, thank you
