### ISSUE TITLE
Correct charge level not displayed in Monterey 12.0-beta (21A5284e)

### ISSUE THREAD

**Issue by napthemax** [davidwernhart/AlDente-Pro-Bug-Tracking#17]
I know I'm running Monterey beta, but could still be valid to keep an eye on for you. AlDente-Pro does not show correct SoC of my computer. It freezes on the level that it have on reboot. See screenshot comparing with CoconutBattery.

<img width="257" alt="Skärmavbild 2021-07-24 kl  08 33 58" src="https://user-images.githubusercontent.com/22963382/126859965-b3377eb8-ebb1-4e20-aed2-5ad0ff65ba56.png">

**Comment by MatthiasKerbl** [comment]
> I know I'm running Monterey beta, but could still be valid to keep an eye on for you. AlDente-Pro does not show correct SoC of my computer. It freezes on the level that it have on reboot. See screenshot comparing with CoconutBattery.
> 
> <img alt="Skärmavbild 2021-07-24 kl 08 33 58" width="257" src="https://user-images.githubusercontent.com/22963382/126859965-b3377eb8-ebb1-4e20-aed2-5ad0ff65ba56.png">

Hi @napthemax,
Try to reinstall AlDente Pro after the update to the macOS Monterey.

**Comment by napthemax** [comment]
Thank you! That did the trick :-)
