### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by RobinDaugherty** [davidwernhart/AlDente-Pro-Bug-Tracking#19]
Running version 1.06
macOS 11.5.1
MacBook Pro (13-inch, M1, 2020)

Seems to happen only when on battery. After quitting and reopening, it continues.

**Comment by badwulfy** [comment]
I confirm I have the same issue with the version 1.06 from SetApp.
I use macOS beta 12.0 (21A5304g).
Several times a day, Al Dente use more than 100% CPU without interruption.

**Comment by dotqwerty** [comment]
Same issue here. This is a bad bug.
<img width="1391" alt="Screenshot 2021-08-18 at 11 58 29" src="https://user-images.githubusercontent.com/64164067/129886846-897b027a-5b6b-48e4-8df5-0f16d97b6d18.png">

**Comment by davidwernhart** [comment]
Hi Guys!

We are aware of this bug and have finally been able to replicate it.
A fix will be released soon!

Thank you for your patience,

David
AppHouseKitchen

**Comment by badwulfy** [comment]
Thank you very much for your help. Take the time you need.

In the meantime, I have disabled Al Dente Pro and re-enabled Apple's battery optimization system.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by falcn** [comment]
>  In the meantime, I have disabled Al Dente Pro and re-enabled Apple's battery optimization system.
I only disable AlDente when I'm on battery. It works correctly when connected to charger.

**Comment by falcn** [comment]
I can confirm that this issue is fixed in 1.07

**Comment by davidwernhart** [comment]
Glad the fix worked for you! Best regards, David

**Comment by RobinDaugherty** [comment]
🌮 🎉 🥇
