### ISSUE TITLE
Awesome beta

### ISSUE THREAD

**Issue by tosbsas** [davidwernhart/AlDente-Pro-Bug-Tracking#2]
So far couldn't find any flaws - will try tree calibrate feature tomorrow and that's about it. All works just fine.

Top Upo - perfect
Discharge - perfect

If you fix the descriptions a bit and add a schedule feature - this is going to be the app of the century - maybe Apple is gonna buy it from you

**Comment by tosbsas** [comment]
checked calibrate - went down to 20 and rose to 100, than back top 80 - perfekt

**Comment by MatthiasKerbl** [comment]
Thanks for the feedback and I am glad it works fine for you. We will definitely take a look at the descriptions again.
