### ISSUE TITLE
Calibrate kills Max charging Setting - beta in sight?

### ISSUE THREAD

**Issue by tosbsas** [davidwernhart/AlDente-Pro-Bug-Tracking#20]
Hi

I know this is a known bug and fix is in the way. Any ATM or Beta to test?

Maybe you should Release 1.06 from setapp to all of us. We paid for ir 😃😃

**Comment by MatthiasKerbl** [comment]
> Hi
> 
> I know this is a known bug and fix is in the way. Any ATM or Beta to test?
> 
> Maybe you should Release 1.06 from setapp to all of us. We paid for ir 😃😃

Hi @tosbsas,

Could you specify which bug you exactly mean by "Calibrate kills Max charging Setting"?
We already released our newest version 1.07 a couple of days ago. :)

**Comment by tosbsas** [comment]
:-)) no problem

When using topup or calibrate maximum charge level changes definitely. I have set it at 80% but after topup it stays at 100. Thats fixed in 1.07 though so you can close the threat.

One more question - I've got a lifetime license - for how many machines can I use it?

Ruben 


_______________________________
Ruben Gutknecht
Lima, Peru
Cel: +51-993491515
Voice/Fax: 49 (0) 721-151-379204 
http://telegram.me/tosbsas
Threema ID: SPEAJUP9
PayPal.me/RubenGutknecht
Deutschland
***@***.***
***@***.***

**Comment by MatthiasKerbl** [comment]
I am glad to hear that. :)

You can use one license on up to 3 MacBooks.

**Comment by tosbsas** [comment]
Hey there

I need to install aldente pro on my new air - where do I get the pro version? I do have a license


_______________________________
Ruben Gutknecht
Lima, Peru
Cel: +51-993491515
Voice/Fax: 49 (0) 721-151-379204 
http://telegram.me/tosbsas
Threema ID: SPEAJUP9
PayPal.me/RubenGutknecht
Deutschland
***@***.***
***@***.***

**Comment by MatthiasKerbl** [comment]
> Hey there I need to install aldente pro on my new air - where do I get the pro version? I do have a license
> […](#)
> _______________________________ Ruben Gutknecht Lima, Peru Cel: +51-993491515 Voice/Fax: 49 (0) 721-151-379204 http://telegram.me/tosbsas Threema ID: SPEAJUP9 PayPal.me/RubenGutknecht Deutschland ***@***.*** ***@***.***

Hi @tosbsas,

You can download it right here in Github: https://github.com/davidwernhart/AlDente/releases/download/1.14/AlDente.dmg

Cheers,
Matthias
