### ISSUE TITLE
Heat protection incorrectly saves user-set value

### ISSUE THREAD

**Issue by falcn** [davidwernhart/AlDente-Pro-Bug-Tracking#22]
I have MacOS Monterey beta (21A5294g) running on MacBook Air M1 2020.
AlDente Pro 1.06 from Setapp.

Steps to reproduce:
1) open settings, enable Heat protection. I have 3° as Max Temp from earlier bugged save.
<img width="360" alt="Screenshot 2021-08-18 at 17 03 44" src="https://user-images.githubusercontent.com/7712803/129914246-d8793b44-e3db-4660-aeb7-1f035a0023a1.png">

2) change "Max Temp" to 36, close settings
3) Heat protection activates, because AlDente uses 3° instead of user-set 36°
<img width="469" alt="Screenshot 2021-08-18 at 17 04 10" src="https://user-images.githubusercontent.com/7712803/129914255-984c95db-3742-40ee-8294-1e699ace823b.png">

4) Close AlDente, reopen Settings. Heat protection is set to 3°
<img width="387" alt="Screenshot 2021-08-18 at 17 04 46" src="https://user-images.githubusercontent.com/7712803/129914259-cc16875e-1152-45ee-ac4e-4ab5e8b73a58.png">

**Comment by MatthiasKerbl** [comment]
Hi @falcn,

You have to press enter after entering a new value in Heat Protection.
I can only reproduce your issue if I only change the value without pressing enter afterward.

**Comment by falcn** [comment]
I pressed "Enter", it still inhibits charging. 
Restarting Aldente resets visible value to 3°.


<img width="440" alt="image" src="https://user-images.githubusercontent.com/7712803/130360207-22874a8e-add8-4896-b652-09335599a1c2.png">

**Comment by falcn** [comment]
Can you tell me where config file is located? I'll try changing it manually

**Comment by falcn** [comment]
By the way, same thing happens to "Sailing mode", it just defaults to 5% after restart no matter what value was entered.

**Comment by MatthiasKerbl** [comment]
Hi @falcn,

Have you tried to completely reinstall AlDente Pro and update to our newest version 1.07?

**Comment by falcn** [comment]
I don't know about 1.07, but 1.10 works. Thank you
