### ISSUE TITLE
After top up battery numbers are not exact anymore

### ISSUE THREAD

**Issue by tosbsas** [davidwernhart/AlDente-Pro-Bug-Tracking#3]
Its wierd

I have set the battery to 80% and it worked perfect there. After using top Up the value is slightly off

![Bildschirmfoto 2021-04-15 um 16 24 47](https://user-images.githubusercontent.com/21263149/114940460-7d5ae280-9e07-11eb-9815-b4a872071480.jpg)

**Comment by tosbsas** [comment]
I tested a bit - what's messing up the numbers a bit is the don't charge when sleep setting. With this turned of you messure is exact, with turned off its 1% off - interesting

**Comment by tosbsas** [comment]
another test :-)) Turned map off over night and disconnected current. On starting the machine AlDente showed 80% but than went to 78 where it stayed and the symbol went to - done. I re-entered 80 in the max value and it charged to 80 and stayed there.

**Comment by MatthiasKerbl** [comment]
I think your MacBook stays below 80% because of the Sailing Mode being activated. You can see that because of the paper plane in the slider. Sailing Mode will keep your MacBook in a charging range and only charge back up to Max. Charge when the lower limit was hit.

**Comment by tosbsas** [comment]
Ok. I see. Thanks for the info
