### ISSUE TITLE
Home call url, needed for the whitelisting

### ISSUE THREAD

**Issue by rimusz** [davidwernhart/AlDente-Pro-Bug-Tracking#30]
Hi @davidwernhart ,
What is the url used to check Pro license?
I'm getting
![Screen Shot 2022-03-01 at 11 47 07](https://user-images.githubusercontent.com/5215395/156149854-e0ffba04-89de-44f6-a76a-9f351ff98686.png)
So I need to get the URL whitelist with out internal systems.
Thanks

**Comment by MatthiasKerbl** [comment]
Hi @rimusz,

There is currently a bug with our licensing service Paddle. Which results in the No connection error message even though you are connected to the internet.

Follow these steps to fix it for now:

1. Go to Settings
2. General Settings
3. Manage License
4. Safe your license code
5. Deactivate License
6. Enter your email address and license code again
7. Activate License

Afterward, it should work again.

We are currently working on a fix with our partner Paddle which will be released with one of the future updates.

Cheers,
Matthias
