### ISSUE TITLE
Battery temperature varies to other apps

### ISSUE THREAD

**Issue by tosbsas** [davidwernhart/AlDente-Pro-Bug-Tracking#4]
Stats says 33° and Al Dente says 30,84° - which one is correct :-))

![Bildschirmfoto 2021-04-15 um 16 28 48](https://user-images.githubusercontent.com/21263149/114940672-c874f580-9e07-11eb-9b1b-72c3f25f251f.jpg)

**Comment by MatthiasKerbl** [comment]
There are a couple of battery temperature sensors. Different apps use different sensors. Therefore, the temperature differs between the apps.

**Comment by tosbsas** [comment]
Weich one do you use?

**Comment by MatthiasKerbl** [comment]
> Weich one do you use?

We will use the same as Coconut Battery in our final release.
