### ISSUE TITLE
Could you open licence preordering?

### ISSUE THREAD

**Issue by verebes1** [davidwernhart/AlDente-Pro-Bug-Tracking#7]
I would like to purchase a lifetime licence. Try the Beta and support AlDente Pro.

I think you would get a lot of interest at the PreOrder Stage.

**Comment by MatthiasKerbl** [comment]
Hi @verebes1,

Due to high demand, the AlDente Pro Beta is already closed. However, you don't have to wait much longer, the final release of AlDente Pro will be soon.

**Comment by MatthiasKerbl** [comment]
> I would like to purchase a lifetime licence. Try the Beta and support AlDente Pro.
> 
> I think you would get a lot of interest at the PreOrder Stage.

Hi @verebes1,

We have just released AlDente Pro 1.0
Check it out: https://apphousekitchen.com/
